Descriptor:
  Name: SquidProxySemantic
  DisplayName: Squid Proxy Insights
  Description: "Plugin para consultas semánticas comunes sobre la tabla SquidProxy_CL (Squid proxy logs) en Sentinel: eventos recientes, búsqueda por IP, resumen de códigos HTTP y destinos más solicitados."
  Icon: https://example.com/squidproxy_icon.png
  Prerequisites: Acceso de lectura a la tabla SquidProxy_CL en el workspace de Sentinel.

SkillGroups:
  - Format: API
    Settings:
      OpenApiSpecUrl: https://REEMPLAZAR_URL_HOSTED/openapi.yaml
    # Autenticación: se usará el contexto delegado (AADDelegated) del usuario en Security Copilot si tiene permisos RBAC.
    Authentication:
      Type: AADDelegated
